version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_fans_crm
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysql_fans_crm
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - nest-network


networks:
  nest-network:
    driver: bridge
